openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
  description: Documentación del módulo de usuarios (User)

paths:
  /users/current:
    get:
      summary: Obtener información del usuario actual
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Usuario actual devuelto correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
        "401":
          description: No autorizado

  /users/create-product:
    post:
      summary: Crear un producto (solo admin)
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Producto creado exitosamente
        "403":
          description: Acceso denegado

  /users/add-to-cart:
    post:
      summary: Agregar producto al carrito (solo usuarios)
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Producto agregado correctamente
        "403":
          description: Acceso denegado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


